trigger:
- main

parameters:
- name: testtag
  displayName: 'Test Tag'
  type: string
  default: 'latest'

stages:
- stage: Deploy
  jobs:
  - job: RithReplaceandDeployment
    steps:
    - checkout: self

    - task: Bash@3
      name: ReplaceTag
      inputs:
        targetType: 'inline'
        script: |
          echo "Hello Rithwik, Replacing image tag in deployment.yaml... check it."
          sed "s|__IMAGETAG__|${{ parameters.testtag }}|g" deployment.yaml > updated-deployment.yaml

    - script: cat updated-deployment.yaml
      displayName: 'Rithwik, Showing the updated file'
