trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: testtagname
    displayName: 'Enter image tag'
    type: string
    default: '20250423'

steps:
- task: Checkout@1

- script: |
    echo "Replacing tag with ${{ parameters.testtagname }}"
    sed -i "s|__IMAGETAG__|${{ parameters.testtagname }}|g" deployment.yaml
  displayName: 'Replace tag in deployment.yaml'

- script: cat deployment.yaml
  displayName: 'Show updated deployment.yaml'
