trigger:
- main

variables:
  testtag: '08'

stages:
- stage: Deploy
  jobs:
  - job: RithReplaceandDeployment
    steps:
    - checkout: self

    - task: Bash@3
      name: Replacing
      inputs:
        targetType: 'inline'
        script: |
          echo "Hello Rithwik, Replacing image tag in deployment.yaml... check it."
          sed "s|__IMAGETAG__|${{ variables.testtag }}|g" deployment.yaml > updated-deployment.yaml

    - script: cat updated-deployment.yaml
      displayName: 'Rithwik, Showing the updated file'
