trigger:
- main

variables:
  imageTag: '77'

stages:
- stage: Deploy
  jobs:
  - job: ReplaceAndDeploy
    steps:
    - checkout: self

    - task: Bash@3
      name: ReplaceTag
      inputs:
        targetType: 'inline'
        script: |
          echo "Replacing image tag in deployment.yaml..."
          sed "s|__IMAGETAG__|${{ variables.imageTag }}|g" deployment.yaml > updated-deployment.yaml

- script: cat deployment.yaml
  displayName: 'Show updated file'
