trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  testtagname: '20250422.5'

steps:
- task: Checkout@1

- script: |
    echo "Replacing tag with $(testtagname)"
    sed -i "s|__IMAGETAG__|$(testtagname)|g" deployment.yaml
  displayName: 'Replace tag in YAML'

- script: cat deployment.yaml
  displayName: 'Show updated file'
